# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:          Norberto Morales
tagline:          
description:      'Quantitative researcher with experience in statistical modeling and data analytics. ![Alt text](C:/Users/Antigone/Pictures/wwoof.jpg)'
url:              http://www.norbertormorales.com
baseurl:          /


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/moralesn/
