# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:Norberto Morales            Hyde
tagline:          ''
description:      'Quantitative researcher with experience in statistical modeling and data analytics.'
url:              http://www.norbertormorales.com
baseurl:          /


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/moralesn/moralesn.github.io
